spring:
    profiles:
        active: prod
    application:
        name: product-service
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            management:
                health:
                    probes:
                        enabled: true
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://auth-server:3202
server:
    port: 3200
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
            instance:
                preferIpAddress: true

